default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  host: db_server

development:
  <<: *default
  database: develop_oreno_sauna

test:
  <<: *default
  database: test_oreno_sauna

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
