default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  host: db_server

development:
  <<: *default
  database: develop_oreno_sauna

test:
  <<: *default
  database: test_oreno_sauna

production:
  database: <%= ENV.fetch('MYSQL_DATBASE') { 'db-name' } %>
  adapter: mysql2
  encodeing: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV.fetch('MYSQL_HOST') { 'host-name' } %>
  username: <%= ENV.fetch('MYSQL_USERNAME') { 'username' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
